/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.classbuilder;
/*import edu.duke.ece651.classbuilder.Course;
import edu.duke.ece651.classbuilder.Faculty;
import edu.duke.ece651.classbuilder.Office;
import edu.duke.ece651.classbuilder.Grade;
import edu.duke.ece651.classbuilder.Test;
import edu.duke.ece651.classbuilder.Deserializer;*/
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
	/*Course c = new Course();
	Faculty f = new Faculty();
	Grade g1 = new Grade();
	Grade g2 = new Grade();

	f.setName("xianghui");
	f.addTaught('e');
	f.addTaught('c');
	c.setInstructor(f);
	g1.setCourse(c);
	g2.setCourse(c);
	g1.setStudent("hm");
	g2.setStudent("sl");
	c.addGrades(g1);
	c.addGrades(g2);
	///t.setInstructor(f);
	///t.setNumStudents(5);
	///t.setX(1);
	///c.toJSON();
	///System.out.println(c.toJSON());*/
	
	/*Test t = new Test();
	t.setX(2);
	System.out.println(t.toJSON());
	JSONObject tjs = t.toJSON();
	Test t0 = Deserializer.readTest(tjs);
	System.out.println(t0.toJSON());*/
        System.out.println(new App().getGreeting());
    }
}
